sonar.verbose=true
sonar.organization=jinu01-key
sonar.projectKey=jinu01-key_jinu-sonaraqube-project
sonar.projectName=saidemytrend
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
